sample:
  property: sample

#spring:
#  config:
#    import: configserver:http://localhost:8191

#spring:
#  config:
#    import: "optional:configserver:"
spring:
  cloud:
    config:
      uri: http://localhost:8888