#Publish Application(Register with Eureka)
eureka:
  instance: # Unique ID for this application instance
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url: # This information must be given to which Eureka Server address the application will connect.
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}


# Fetch configuration from Spring Cloud Config Server
spring:
  cloud:
    config:
      fail-fast: true # Fail startup if config server connection fails (optional)
      retry:
        max-attempts: 30 # Retry retrieving config up to 30 times
        max-interval: 8000 # Wait up to 8 seconds between retries

# Send all requests to Zipkin for tracing (adjust probability for production)
management:
  tracing:
    sampling:
      probability: 1.0 # Sample ALL requests for traces (high overhead in production)
  zipkin:
    tracing: # Send tracing data to Zipkin server at this address
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}


