#Publish Application(Register with Eureka)
eureka:
  instance: # instance id for eureka server
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url: # This information must be given to which Eureka Server address the application will connect.
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      fail-fast: true #it may be desirable to fail the startup of a service if it cannot connect to the Config Server.
      retry:
        max-attempts: 30 # retry configuration retrieval up to 100 times
        max-interval: 8000 # max backoff interval

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
