sample:
  property: sample
  value: example

#Publish Application(Register with Eureka)
eureka:
  instance: # instance id for eureka server
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url: # This information must be given to which Eureka Server address the application will connect.
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
